### ISSUE TITLE
You might want to base off of release instead

### ISSUE THREAD

**Issue by K4sum1** [rustdevbtw/flamewolf#1]
I notice this is forked off the master or nightly branch. You might want to go for release instead.

**Comment by rustdevbtw** [comment]
Well, that's a good idea, but FlameWolf is detached from the source completely, so it's a bit hard to rebase. Now, if I rebase it off the release, I'll be reducing features (but increasing stability, ofc). I do think it'll be a good idea to rebase, and will probably do so when the next time I merge back changes. Before that, I also plan to get CI (on GitHub) done, for automated builds and testing.

-- 
regards,
rajdeep

> I notice this is forked off the master or nightly branch. You might want to go for release instead.

Well, that's a good idea, but FlameWolf is detached from the Firefox source completely, so it's a bit hard to rebase. Now, if I rebase it off the release, I'll be reducing features (but increasing stability, ofc). I do think it'll be a good idea to rebase, and will probably do so when the next time I merge back changes. Before that, I also plan to get CI (on GitHub) done, for automated builds and testing.

-- 
regards,
rajdeep

**Comment by K4sum1** [comment]
> Before that, I also plan to get CI (on GitHub) done, for automated builds and testing.

I am interested in doing this for my fork too. I would want to have a nightly fork with automated builds, however I'm not sure if I can automate updating or rebasing source.

Also what do you plan for this browser? I have a few things I want to do, however don't really have the time or knowledge to do. I'm wondering if maybe you would be interested in implementing them in your browser and I could clone the changes.

**Comment by rustdevbtw** [comment]
> I am interested in doing this for my fork too. I would want to have a nightly fork with automated builds, however I'm not sure if I can automate updating or rebasing source.

That's great! For FlameWolf, while builds will be automated, rebases and updates won't. They'll require manual review to ensure that every patch is correctly there.


> Also what do you plan for this browser? I have a few things I want to do, however don't really have the time or knowledge to do. I'm wondering if maybe you would be interested in implementing them in your browser and I could clone the changes.

My plans for FlameoWolf are simple:
- make it privacy-friendly, by default.
- have sensible defaults in it.
- some additional new features for websites to use.

Additionally, I'm open to ideas!

**Comment by K4sum1** [comment]
> rebases and updates won't. They'll require manual review to ensure that every patch is correctly there.

Yeah, probably fair. My thinking for my fork is that all the breaking changes are mostly done, and if something pops up, it'll either be a conflict I need to manually resolve or quickly noticed. Although idk maybe you're right.

> Additionally, I'm open to ideas!

Here's some generic issues for things that might arise, wanting to gather community information:
Remove Telemetry - https://github.com/Eclipse-Community/r3dfox/issues/6
More browser optimizations - https://github.com/Eclipse-Community/r3dfox/issues/43

Adding back removed features:
Adobe Flash/NPAPI support - https://github.com/Eclipse-Community/r3dfox/issues/65
Add back FTP support - https://github.com/Eclipse-Community/r3dfox/issues/70
Add back UserAgentOverrides.jsm (I'll probably get around to this myself) - https://github.com/Eclipse-Community/r3dfox/issues/67

Bringing back ability to disable e10s or run in single process mode: (Probably will be relatively easy to fix myself but tedious)
Improve non-e10s mode or truly reduce to single process - https://github.com/Eclipse-Community/r3dfox/issues/82
Disabling e10s breaks video player - https://github.com/Eclipse-Community/r3dfox/issues/83
Disabling e10s breaks about:logins - https://github.com/Eclipse-Community/r3dfox/issues/84

Misc things:
Setting up update server - https://github.com/Eclipse-Community/r3dfox/issues/1
Adding ffmpeg or similar to browser - https://github.com/Eclipse-Community/r3dfox/issues/9
Make failed downloads have red tint or background color - https://github.com/Eclipse-Community/r3dfox/issues/104
Option to just go to link instead of switching to old tab if already open - https://github.com/Eclipse-Community/r3dfox/issues/105
Open tab counter from Wavefox (I'll probably get around to this myself) - https://github.com/Eclipse-Community/r3dfox/issues/76
Simple Setup UA (from Floorp) (I'll probably get around to this myself) - https://github.com/Eclipse-Community/r3dfox/issues/94
Add Waterfox tab features (I'll probably get around to this myself) - https://github.com/Eclipse-Community/r3dfox/issues/96

**Comment by rustdevbtw** [comment]
> Yeah, probably fair. My thinking for my fork is that all the breaking changes are mostly done, and if something pops up, it'll either be a conflict I need to manually resolve or quickly noticed. Although idk maybe you're right.

Well, my approach is to:
1. Download the Flamewolf and Firefox source code
2. Remove their VCS files
3. Diff them
4. Copy newly added files from the Firefox for to flamewolf
5. Resolve changes to others
6. At last, make sure that `diff -r` shows no change between the Firefox and FlameWolf dirs, aka keep them in equilibrium.
7. Add the Flamewolf VCS files back
8. Commit + Push

The actual time-consuming part is the #5. I do stuff to copy files from the Firefox dir to flamewolf automatically if I know that I haven't changed anything in it, an that saves time. I believe this whole process could be optimized further.

**Comment by rustdevbtw** [comment]
> Here's some generic issues for things that might arise, wanting to gather community information:
Thanks! I'll take a look at them!

**Comment by K4sum1** [comment]
> Before that, I also plan to get CI (on GitHub) done, for automated builds and testing.

What happened to this?

**Comment by rustdevbtw** [comment]
> > Before that, I also plan to get CI (on GitHub) done, for automated builds and testing.
> 
> What happened to this?

That's what I'm doing rn. The build is currently running (it's gonna take ~3h)

**Comment by K4sum1** [comment]
I don't see any of the UI elements for GitHub actions though.

**Comment by K4sum1** [comment]
Nevermind, idk why they're not showing on commits. I had to go to the Actions tab.

**Comment by K4sum1** [comment]
> For Windows, it needs MozillaBuild, and I'm yet to figure it out (I can't also test that myself because I don't use Windows).

Oh, I would be mostly interested in Windows builds since that is all I build for.

However supposedly this could be used for cross compilation from Linux, but I'm not sure how to use it.
https://github.com/Eclipse-Community/r3dfox/blob/release/mozconfigs/mozconfig-win-cross

**Comment by rustdevbtw** [comment]
> > For Windows, it needs MozillaBuild, and I'm yet to figure it out (I can't also test that myself because I don't use Windows).
> 
> Oh, I would be mostly interested in Windows builds since that is all I build for.
> 
> However supposedly this could be used for cross compilation from Linux, but I'm not sure how to use it.
> https://github.com/Eclipse-Community/r3dfox/blob/release/mozconfigs/mozconfig-win-cross

Cross Compilation is an option, but I've had a bad experience in the past, where I've seen them build perfectly fine, only to break unexpectedly, or just outright not work. I'll give it a go, and try with Wine. If it goes well, I'll ask my friends to test it. If everything goes well, I'll update the workflow, and manually upload the Windows Artifacts.

**Comment by K4sum1** [comment]
> and manually upload the Windows Artifacts.

Why manually? Doesn't it allow for automatic artifact uploads?

**Comment by rustdevbtw** [comment]
> > and manually upload the Windows Artifacts.
> 
> Why manually? Doesn't it allow for automatic artifact uploads?

It does, but the workflow run for building for Linux is already running. If I'm to let that happen for Windows artifacts, then I'll need to make sure it detects that the Linux artifact exists (the cache can help with that), and not build for that. Otherwise, I'll need to recreate the tag + release, to let the workflow trigger again. I'll also use `workflow_dispatch` to trigger that manually. Also, I can just provide the inputs to build for Windows, if I use the workflow_dispatch. I'll try it.

**Comment by K4sum1** [comment]
Oh, ok. If you get it working, I might need help setting it up for my repo. I would like to run it on the nightly branch for every commit, or the last commit in a batch upload.

**Comment by rustdevbtw** [comment]
> Oh, ok. If you get it working, I might need help setting it up for my repo. I would like to run it on the nightly branch for every commit, or the last commit in a batch upload.

Happy to help :)
Just be prepared, though, it'll take at least a few hours for every build, so building off every commit isn't probably a good idea. Mozilla themselves build off the Nightly branch every 12 hours, afaik. Also, caching is gonna help you a lot (except the first build, ofc)

**Comment by K4sum1** [comment]
> so building off every commit isn't probably a good idea.

I'll probably do a rebase every day and commit the changes then. I don't assume I'll be building every single commit unless that's just how actions works idk.

**Comment by K4sum1** [comment]
> I don't assume I'll be building every single commit unless that's just how actions works idk.

Yeah GitHub Actions only builds the last commit in a batch upload, so I'm good here.

**Comment by K4sum1** [comment]
A bit unrelated, but I have been having an issue with GitHub issues with another project. Do you know how to do this?

https://github.com/orgs/community/discussions/126731

**Comment by rustdevbtw** [comment]
> A bit unrelated, but I have been having an issue with GitHub issues with another project. Do you know how to do this?
> 
> https://github.com/orgs/community/discussions/126731

I couldn't understand what the problem was (probably because I'm mostly unaware of Windows API nuances). Is it like some Windows version compatibility problem?

**Comment by K4sum1** [comment]
Yeah, the goal is Windows 7 support, and Windows 7 doesn't have those functions.

I don't want to go out and directly say it as the internet is filled with 10tards.

**Comment by rustdevbtw** [comment]
> Yeah, the goal is Windows 7 support, and Windows 7 doesn't have those functions.
> 
> I don't want to go out and directly say it as the internet is filled with 10tards.

So, does cross-compiling from Linux fix it? (Afaik, there's no Windows 7 runner available for GHA)

**Comment by K4sum1** [comment]
> So, does cross-compiling from Linux fix it? (Afaik, there's no Windows 7 runner available for GHA)

The issue is hb.dll, which I think can only be cross compiled.
