### ISSUE TITLE
Use Firefox's default UA instead of Custom Flamewolf UA.

### ISSUE THREAD

**Issue by indprtech** [rustdevbtw/flamewolf#12]
**Flamewolf Version : 128.1.0**

**Expected Result:**
The UA Should be `Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.1.0`

**Actual Result:**
The UA is `Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 FlameWolf/128.1.0`

**Why?**
Because Custom Browsers are not known-browsers some websites such as `google.com` interept the browser as the oldest browsers and in worst-cases Insecure Browser

**Comment by rustdevbtw** [comment]
It is coming in v128.1.1 (probably today). As a workaround, setting `general.useragent.compatMode.firefox` (in `about:config`) to `true` will tell Flamewolf to automatically append the `Firefox/` part to it.
